CARE-275: Add spell-checking build
Lombiq/GitHub-Actions pull request #114
Opened 2022-11-22 22:06 UTC by adelgeiszt

[CARE-275](https://lombiq.atlassian.net/browse/CARE-275): Add spell-checking build

2022-11-30 10:15 UTC, 0liver requested changes

2022-11-30 10:15 UTC, 0liver commented on .github/workflows/spelling.yml
> -        run: |
Why did you outdent these steps? The [main example](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/build-dotnet/action.yml#L67) we have in GHA uses the previous indentation. Same below.

2022-11-30 11:41 UTC, adelgeiszt commented on .github/workflows/spelling.yml
> -        run: |
Fixed it, sorry.

2022-11-30 20:36 UTC, 0liver requested changes

2022-11-30 20:36 UTC, 0liver commented on .github/workflows/spelling.yml
> +        uses: Lombiq/GitHub-Actions/.github/actions/checkout@issue/CARE-265
This can now be `@dev` again, since the `CARE-265` branch has been merged.

2022-12-02 08:37 UTC, 0liver approved these changes

2022-12-02 09:12 UTC, merged