OSOE-562: Add sensible timeouts to all reusable workflows in Lombiq.GitHub.Actions
Lombiq/GitHub-Actions pull request #204
Opened 2023-02-08 08:19 UTC by adelgeiszt

OSOE-562: Add sensible timeouts to all reusable workflows in Lombiq.GitHub.Actions

2023-02-12 09:01 UTC, dministro requested changes

2023-02-12 09:01 UTC, dministro commented on .github/workflows/create-jira-issues-for-community-activities.yml
> +        default: 21
```suggestion
        default: 3
```
I feel 21 min a bit too much as the default here. See: https://github.com/Lombiq/Orchard-UIKit/actions/workflows/create-jira-issues-for-community-activities.yml

2023-02-12 09:01 UTC, dministro commented on .github/workflows/validate-pull-request.yml
> +        default: 10
```suggestion
        default: 3
```
10 min is too much.
See: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/workflows/validate-pull-request.yml

2023-02-12 09:01 UTC, dministro commented on .github/workflows/validate-submodule-pull-request.yml
> +        default: 10
```suggestion
        default: 3
```
10 min is too much.
See: https://github.com/Lombiq/Orchard-UIKit/actions/workflows/validate-pull-request.yml

2023-02-12 18:35 UTC, adelgeiszt commented on .github/workflows/create-jira-issues-for-community-activities.yml
> +        default: 21
Fair point, 21 might be too high. It hits 4 minutes [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/workflows/create-jira-issues-for-community-activities.yml?page=4) and 14 minutes [here](https://github.com/Lombiq/GitHub-Actions/actions/workflows/create-jira-issues-for-community-activities-in-this-repo.yml?page=2). Also 3 minutes once in OSOCE. So maybe the default could be 5 or 6 minutes?

2023-02-17 12:52 UTC, dministro commented on .github/workflows/create-jira-issues-for-community-activities.yml
> +        default: 21
Sorry, I didn't get a notification about your comment. Yes, I can agree with 5min.

2023-02-18 10:01 UTC, dministro approved these changes

2023-02-18 10:01 UTC, dministro commented on .github/workflows/post-pull-request-checks-automation.yml
> +        uses: Lombiq/GitHub-Actions/.github/actions/auto-merge-pull-request@issue/OSOE-562
Targeting the issue branch for actions is not necessary, since the actions have not changed.

2023-02-18 10:09 UTC, merged