Fixing that Create Jira issues for community activities doesn't work for external pull requests
Lombiq/GitHub-Actions pull request #252
Opened 2023-09-04 18:56 UTC by Piedone

2023-09-04 18:58 UTC, Piedone commented on .github/actions/create-jira-issues-for-community-activities/action.yml
> +        }
No logic changes, just the original line was too long.

2023-09-05 11:07 UTC, DAud-IcI requested changes

2023-09-05 11:07 UTC, sarahelsaig commented on .github/actions/create-jira-issues-for-community-activities/action.yml
> +        # Even though the trigger is pull_request_target, the event is pull_request.
```suggestion
        # Even though the trigger is pull_request_target, the event payload is pull_request (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target).
```

2023-09-05 11:20 UTC, DAud-IcI approved these changes

2023-09-05 21:20 UTC, merged