OSOE-517: Add merge queue support for verifying GitHub Action expected refs
Lombiq/GitHub-Actions pull request #292
Opened 2023-12-03 04:25 UTC by davidpuplava

Adds support for merge queues to run the [`validate-this-gha-refs` workflow](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/validate-this-gha-refs.yml) when a pull request is added to the merge group, if the repository is configured for it.

Adds a `skipReviewApproval` flag to the [`Determine Expected Ref for GitHub Actions Files` step](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/validate-this-gha-refs.yml#L69) of the `validate-this-gha-refs` workflow that changes the default behavior of expecting the base branch ref (e.g. `@dev`) when the Pull Request is approved (using GitHub's pull request review feature). This allows additional commits on the PR branch after review approval but before adding the PR to the merge queue.

Here is a reminder on how the `validate-this-gha-refs` currently behaves:
1. When a PR is submitted and/or has additional commits, and prior to PR Approval, the expected refs are the target branch e.g. `@issue/OSOE-517`.
2. After PR Review approval, the expected refs are the base branch e.g. `@dev` so that the developer or reviewer can make sure the refs are changed back to `dev` prior to merging the pull request.

Here is how this PR changes the `validate-this-gha-refs` behavior:
1. Same as above. When a PR is submitted and/or has additional commits, and prior to PR Approval, the expected refs are the target branch e.g. `@issue/OSOE-517`.
2. If and only if, the [`skipReviewApproval` flag](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-517/.github/workflows/validate-this-gha-refs.yml#L92) is set to False, will the behavior be the same as above. After PR approval, the expected refs are the base branch e.g. `@dev` so that the developer or reviewer can make sure the refs are changed back to `dev` prior to merging the pull request.
3. For LGHA, [`skipReviewApproval` flag](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-517/.github/workflows/validate-this-gha-refs.yml#L92) is set to True to align with how PRs can get a PR Review approval but receive additional commits before wanting to enforce the base branch refs, e.g. `@dev`.
4. Enforcing the base branch ref (e.g. `@dev`) happens after the PR is added to the merge queue (i.e. when the "Merge When Ready" button is clicked. **NOTE** I believe for this to work, you have to configure the merge queue to run the `validate-this-gha-refs` workflow as a status check.

This PR essentially changes the "signal" for approval from PR Review Approval to adding it to the Merge Queue (clicking the Merge When Ready button).

2023-12-04 00:13 UTC, DemeSzabolcs requested changes

2023-12-04 00:13 UTC, DemeSzabolcs commented on .github/workflows/validate-this-gha-refs.yml
> +        uses: LavaTG/LGHA/.github/actions/check-merge-queue-adds@dev
I can't access this action, I think it's in a private repository or something, so I can't check it. Also when we are using actions from somewhere else we do this:

> For non-GitHub actions (which start with actions/) always pin the action to a specific full-length commit SHA, not a version tag, since [this ensures that we use it in a secure state that we've vetted](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions). For readability, also comment the version there.

2023-12-04 00:14 UTC, DemeSzabolcs commented on .github/workflows/validate-this-gha-refs.yml
> +        uses: LavaTG/LGHA/.github/actions/check-merge-queue-adds@dev
It's also failed here: https://github.com/Lombiq/GitHub-Actions/actions/runs/7080272095/job/19267925620?pr=292#step:1:35

2023-12-04 05:02 UTC, davidpuplava commented on .github/workflows/validate-this-gha-refs.yml
> +        uses: LavaTG/LGHA/.github/actions/check-merge-queue-adds@dev
Thank you. Yes, that repo is what I used for development. It was public while I developed and like when I first submitted the PR. The [`check-merge-queue-adds` action](https://github.com/Lombiq/GitHub-Actions/tree/issue/OSOE-517/.github/actions/check-merge-queue-adds) I added to the Lombiq repo but forgot to change this reference.

2023-12-04 21:08 UTC, DemeSzabolcs approved these changes

2023-12-04 21:10 UTC, DemeSzabolcs commented
I approved the PR but we got this error here: https://github.com/Lombiq/GitHub-Actions/actions/runs/7092583727/job/19304192097?pr=292#step:11:27

2023-12-04 22:28 UTC, davidpuplava commented
Ok, I'll take a look - for some reason the head and base refs are both empty which is unexpected.

2023-12-08 23:06 UTC, davidpuplava commented
> I approved the PR but we got this error here: https://github.com/Lombiq/GitHub-Actions/actions/runs/7092583727/job/19304192097?pr=292#step:11:27

I fixed the above error.

In consolidating the [Verify GitHub Actions Items Match Expected Ref](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-517/.github/workflows/validate-this-gha-refs.yml#L113) step, I overlooked that on a `pull_request_review` event, the `head` and `base` refs come from a different context than the `github` context. This [if/else block](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-517/.github/workflows/validate-this-gha-refs.yml#L86) in the [Determine Expected Ref for GitHub Actions Files](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-517/.github/workflows/validate-this-gha-refs.yml#L79) now covers the PR approval and Merge Group approval cases.

2023-12-09 14:35 UTC, DemeSzabolcs approved these changes

2023-12-09 14:37 UTC, DemeSzabolcs commented
Okay, I approved it, now I will try to merge it and it should fail, because I haven't changed the action branches'.

2023-12-09 14:37 UTC, merged

2023-12-09 14:41 UTC, DemeSzabolcs commented
@davidpuplava 
Well the validate GHA refs failed: https://github.com/Lombiq/GitHub-Actions/actions/runs/7151812876
But it still merged the branch: 
![image](https://github.com/Lombiq/GitHub-Actions/assets/80963259/db4e6f8c-0c4e-4242-be3a-8801c96c4403)

Shouldn't this also prevent the merge?

(BTW I'm reverting the merge for now.)

2023-12-09 20:05 UTC, davidpuplava commented
@DemeSzabolcs I think this might be a settings issue because I don't see a workflow action run triggered by the add to the merge queue. Under `All workflows` on the `Actions` tab, we should a `Validate GitHub Actions Refs #XX: Merge group checks requested` but I don't see it in LGHA's repo. Here is a screenshot from my test repo:
![image](https://github.com/Lombiq/GitHub-Actions/assets/5144137/a1c916d3-0360-425d-9393-b9cd896c0441)

Can you check and confirm the branch protection rule for `dev` has the `Require status checks to pass before merging` and that `validate-gha-refs` is listed under the `Status checks that are required`? Here is a screenshot of my test repo that uses merge queues with the required status checks.
![image](https://github.com/Lombiq/GitHub-Actions/assets/5144137/28a505d2-eca0-4e5f-baf8-572e40152f1b)

The workflow run where the validate GHA refs failed (https://github.com/Lombiq/GitHub-Actions/actions/runs/7151812876) is from the push to the `dev` branch which also triggers a check to make sure all the refs point back to `@dev`.

2023-12-09 20:24 UTC, DemeSzabolcs commented
Thank you, I see! I can't check that. @BenedekFarkas, or @Piedone could you please check it?

> Can you check and confirm the branch protection rule for dev has the Require status checks to pass before merging and that validate-gha-refs is listed under the Status checks that are required? Here is a screenshot of my test repo that uses merge queues with the required status checks.

2023-12-12 08:48 UTC, BenedekFarkas commented
Thanks, I've just set this up for this repo. Please confirm that this means that after approving the PR, `validate-gha-refs` will still fail if any of the workflow branch references aren't pointing to `dev`, but it won't allow merging the PR because of that, only after restoring the branch references to `dev` and the check is successful.

2023-12-12 14:17 UTC, DemeSzabolcs commented
@davidpuplava Please open another PR, with the same changes as this one and we can test it.