OSOE-862: Auto-merge `release` branches to `dev`
Lombiq/GitHub-Actions pull request #358
Opened 2024-05-20 18:38 UTC by Piedone

[OSOE-862](https://lombiq.atlassian.net/browse/OSOE-862)
Fixes #357

[OSOE-862]: https://lombiq.atlassian.net/browse/OSOE-862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-05 17:54 UTC, BenedekFarkas requested changes

2024-06-05 17:54 UTC, BenedekFarkas commented on Readme.md
> +To create a new release, create a new branch following the above naming convention at the commit to be released and push it. Take this similar to how you would add a release tag in other repos, and d
```suggestion
To create a new release, create a new branch following the above naming convention at the commit to be released and push it. This is similar to how you would add a release tag in other repos, and don't push anything else to the release branch.
```

2024-06-05 17:54 UTC, BenedekFarkas commented on .github/workflows/tag-version.yml
> +          commit_message: Merge remote-tracking branch '${{ inputs.expected-ref }}' into ${{ inputs.expected-ref }}
```suggestion
          commit_message: Merge remote-tracking branch '${{ inputs.expected-ref }}' into ${{ inputs.merge-target }}
```

2024-06-06 12:16 UTC, Piedone commented on .github/workflows/tag-version.yml
> +          commit_message: Merge remote-tracking branch '${{ inputs.expected-ref }}' into ${{ inputs.expected-ref }}
Oh yeah, indeed.

2024-06-06 13:43 UTC, BenedekFarkas approved these changes

2024-06-06 13:48 UTC, merged