Removing obsolete ui-test-parallelism
Lombiq/GitHub-Actions pull request #406
Opened 2024-12-22 01:18 UTC by Piedone

2025-01-22 04:03 UTC, Piedone commented on .github/actions/test-dotnet/Merge-BlameHangDumps.ps1
> +    if (-not $allow -and $TestConfiguration)
I'm not sure about this, but this seems to be the original intent: `if NOT $allow and if $TestConfiguration is set`.

2025-02-11 21:42 UTC, dministro requested changes

2025-02-11 21:42 UTC, dministro commented on .github/actions/test-dotnet/Merge-BlameHangDumps.ps1
> +        Copy-Item -Path $PSItem.FullName -Destination $destinationDirectory
I used `Move-Item` here because - during the development - some runs ended with a `not enough free disk space` error. I don't know if this is still the case. Please consider to keep the `Move-Item` approach.

2025-02-12 00:01 UTC, Piedone commented on .github/actions/test-dotnet/Merge-BlameHangDumps.ps1
> +        Copy-Item -Path $PSItem.FullName -Destination $destinationDirectory
I changed this because some ZAP files of the ZAP reports remained access denied, despite all my efforts (visible in the history, but I made sure that ZAP is absolutely shut down, also the whole of Docker, no other process is accessing the files, the permissions are correct). That broke blame hang dump collection in every single OSOCE run. I don't see any other solution than copying.

A blame hang dumps is less than a GB, BTW (see e.g. https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/12901077411), that should not be an issue even on a 2-core standard runner, let alone any larger ones (and all public projects on GitHub get the 4-core ones with more space).

2025-02-13 22:08 UTC, dministro approved these changes

2025-02-13 22:10 UTC, merged